### ISSUE TITLE
Issues in the events analysis module

### ISSUE THREAD

**Issue by Igor-ID** [N-Nieto/Inner_Speech_Dataset#11]
1. The Check_Baseline_tags function works incorrectly when comparing events[3,2]==14. This is never true since each session starts with: [11, 13, 14, 15, 21...], which means that the third element is always 15. As a result, the function always adds event #14 to the 14th position of the initial event array. (see Image 1)
2. The Event_correction function shows strange behavior when it detects a concentration control question event (tag #61-64). In the normal case, the sequence looks like 17 61 42, but when it detects the absence of 17 before 61 the function adds 42 instead of 17, so the corrected sequence looks like 42 61 42. (see Image 2)

![Screenshot 2022-06-02 020043](https://user-images.githubusercontent.com/69838126/171605764-f6af4ea4-9ad5-4e1d-afb9-1fcb2d552588.png)
Image 1

![Screenshot 2022-06-02 023001](https://user-images.githubusercontent.com/69838126/171605758-1e66f659-e2ae-4164-aca8-435d5d56cbb6.png)
Image 2

**Comment by N-Nieto** [comment]
Hello Igor, thanks for your comments!

Are you using the InnerSpeech_preprocessing.py script? All the developed code is made to be used within that script and does not work otherwise.

When loading participant 10 in block 1 (that have and special load), the end of the Baseline is missing (tag 14) and the "Check_Baseline_tags" function is made for correct this missing tag. The function adds the missing tag 15 second after the start of Baseline (tag 13).

The events starts as [65536, 11, 13, 14, 15...]. The 65536 event is a starting event made by the acquisition system and is deleted in the "Event_correction" function later. The function "Check_Baseline" needs to run *before* the "Event_Correction", as it is in the "InnerSpeech_preprocessing". Otherwise it will fail.

Thanks for the observation regarding the cognitive control questions, I just update the function!

I hope this helps! Let me know if you have an other question,

Best, 

Nico
